using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using PgBackupManager.Core.Models;

namespace PgBackupManager.Core.Services;

public sealed class RestoreOptions
{
    public string Host { get; set; } = "";
    public int Port { get; set; } = 5432;
    public string Database { get; set; } = "";
    public string Username { get; set; } = "";
    public string BackupFile { get; set; } = "";

    public bool SingleTransaction { get; set; } = true;
    public bool CleanFirst { get; set; }
    public bool NoOwner { get; set; } = true;
    public bool NoPrivileges { get; set; } = true;

    // Parallel restore workers. pg_restore refuses to combine --jobs with
    // --single-transaction (mutually exclusive at the Postgres level) — callers
    // must ensure SingleTransaction is off whenever Jobs > 1, this class does
    // not silently override either setting.
    public int Jobs { get; set; } = 1;

    // FULL-FIDELITY restore (recommended): hand whole schemas to pg_restore so it
    // brings EVERYTHING — table data, indexes, constraints, sequences values,
    // triggers, defaults — in the correct dependency order. Nothing is filtered.
    //   • RestoreEntireFile = true  → restore the complete archive (all schemas in it)
    //   • IncludeSchemas    = [..]  → restore only these schemas, but each in full
    public bool RestoreEntireFile { get; set; }
    public IReadOnlyList<string>? IncludeSchemas { get; set; }

    // ADVANCED object-level cherry-pick (definitions only — may omit data). Only
    // used when the two full-fidelity options above are not set.
    public IReadOnlyList<TocEntry>? SelectedToc { get; set; }
    public IReadOnlyList<TocEntry>? AllToc { get; set; }
}

public sealed class PgRestoreRunner
{
    public ProcessRunner Process { get; } = new();

    public async Task<int> RunAsync(string pgRestoreExe, RestoreOptions opts, string plaintextPassword, CancellationToken ct = default)
    {
        var args = new List<string>
        {
            $"--host={opts.Host}",
            $"--port={opts.Port}",
            $"--username={opts.Username}",
            $"--dbname={opts.Database}",
            "--verbose",
            "--no-password",
        };

        if (opts.SingleTransaction) args.Add("--single-transaction");
        if (opts.CleanFirst) { args.Add("--clean"); args.Add("--if-exists"); }
        if (opts.Jobs > 1) args.Add($"--jobs={opts.Jobs}");
        if (opts.NoOwner) args.Add("--no-owner");
        if (opts.NoPrivileges) args.Add("--no-privileges");

        string? listFile = null;

        if (opts.RestoreEntireFile)
        {
            // Whole archive — pg_restore handles all objects + data + ordering. Faithful.
        }
        else if (opts.IncludeSchemas is { Count: > 0 })
        {
            // Whole schema(s), in full. No --use-list, so data/indexes/constraints all come.
            //
            // UNQUOTED, deliberately — unlike pg_dump's --schema (which pattern-matches
            // against the live catalog and correctly un-quotes a "quoted identifier"),
            // pg_restore's --schema does a plain literal string compare against the
            // namespace recorded in the archive's TOC. Wrapping the name in embedded
            // double quotes here makes it compare "\"name\"" against the TOC's bare
            // "name" — that never matches, so 0 entries get selected, pg_restore prints
            // "implied data-only restore", and the run "succeeds" in seconds having
            // restored nothing. Confirmed empirically with pg_restore --list against a
            // real archive: quoted = 0 matches, unquoted = full match (even for a schema
            // whose name itself contains a dot, e.g. "singularity.membership" — pg_restore
            // does not split --schema on dots the way pg_dump's pattern parser does).
            foreach (var s in opts.IncludeSchemas) args.Add($"--schema={s}");
        }
        else if (opts.SelectedToc != null && opts.AllToc != null && opts.SelectedToc.Count > 0)
        {
            // Advanced cherry-pick (definitions only).
            listFile = Path.Combine(Path.GetTempPath(), $"pgrestore_{System.Guid.NewGuid():N}.list");
            var selectedIds = new HashSet<int>(opts.SelectedToc.Select(t => t.DumpId));
            var sb = new System.Text.StringBuilder();
            sb.AppendLine(";");
            sb.AppendLine("; Filtered TOC generated by PgBackupManager");
            sb.AppendLine(";");
            foreach (var entry in opts.AllToc)
            {
                if (selectedIds.Contains(entry.DumpId)) sb.AppendLine(entry.RawLine);
                else sb.AppendLine(";" + entry.RawLine);
            }
            await File.WriteAllTextAsync(listFile, sb.ToString(), ct);
            args.Add($"--use-list={listFile}");
        }

        args.Add(opts.BackupFile);

        var env = new Dictionary<string, string> { ["PGPASSWORD"] = plaintextPassword };
        try
        {
            return await Process.RunAsync(pgRestoreExe, args, env, ct: ct);
        }
        finally
        {
            if (listFile != null && File.Exists(listFile))
                try { File.Delete(listFile); } catch { }
        }
    }
}
